# Алгебраические коды

## Терминология

Будем называть кодом некоторое пространство $C$ над полем $F$.

Линейным блоковым кодом будем называть $k$-мерное подпространство $n$-мерного векторного пространства над полем $GF(q)$.

## Информационная совокупность

Информационная совокупность кода $C$ над полем $F$ это такое минимальное подмножество координат $J$, что все элементы $F^{|J|}$ в этих координатах различны.

Информационная совокупность линейного кода $C \subset \mathbb{F}_q^n$ это такое множество координат $J = \{j_1, j_2,  \dots j_k\}$, что для любого $f \in \mathbb{F}_q^k$ существует единственное кодовое слово $c \in C$ такое, что для всех $i \in [1, k]$ верно $c_{j_i} = f_i$.

Проверочной совокупностью называются все координаты, не являющиеся информационными.

## Декодирование по информационным совокупностям

Пусть $y = c + e$, где $c$ — исходный вектор, $y$ — принятый вектор, а $e$ — вектор ошибки. Информационная совокупность $J$ называется свободной от ошибок, если для всех $i \in J$ верно $e_i = 0$. Если её удалось найти, то можно восстановить $c$ (исходя из определения $J$).

Общий алгоритм декодирования следующий. Пройдёмся по всем возможным $J$. Вычислим для каждой $J$ восстановленный вектор $c_J$. Результатом будет являться $\underset{c_J}{argmin} d_H(c_J, y)$.

Для линейных кодов каждая возможная информационная совокупность $J$ соответствует некоторой матрице $G_J$, полученной из порождающей матрицы $G$ путём комбинации линейных преобразований над строками, такой, что столбцы с позициями из $J$ образуют единичную матрицу в $G_J$. Тогда $c_J = y_J \cdot G_J$.

Далее будет показан пример перебора таких информационных совокупностей.

In [1]:
from algebra.binary import binary_array

g = binary_array([[1] * 8 + [0] * 8, ([1] * 4 + [0] * 4) * 2, ([1] * 2 + [0] * 2) * 4, [1, 0] * 8, [1] * 16])
print("g:")
print(g)

def generate_j(g_j):
    n, m = len(g_j), len(g_j[0])
    j = [None] * n
    for i in range(0, m):
        if sum([1 if g_j[k][i] == 1 else 0 for k in range(n)]) == 1:
            j[max([k if g_j[k][i] == 1 else 0 for k in range(n)])] = i
    return j

y = binary_array([1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0])
print("y: " + str(y))

g:
[[1 1 1 1 1 1 1 1 0 0 0 0 0 0 0 0]
 [1 1 1 1 0 0 0 0 1 1 1 1 0 0 0 0]
 [1 1 0 0 1 1 0 0 1 1 0 0 1 1 0 0]
 [1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0]
 [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]]
y: [1 1 0 0 0 0 0 1 1 1 0 0 1 0 1 0]


In [2]:
from algebra.binary import to_array
import numpy as np

g1 = np.copy(g)
g1 += np.array([g1[0] if i != 0 else [0] * len(g1[0]) for i in range(len(g1))])
g1[0] += g1[3]
g1[0] += g1[2]
g1[3] += g1[1]
print("g_1:")
print(g1)

j1 = generate_j(g1)
yj1 = np.array([y[pos] for pos in j1])
print("j_1: " + str(j1))
print("y_j1: " + str(yj1))

c1 = yj1 @ g1
e1 = y - c1
print("c_1: " + str(c1))
print("e_1: " + str(e1))
print("d_1: " + str(sum(to_array(e1))))

g_1:
[[1 0 0 1 1 0 0 1 0 1 1 0 0 1 1 0]
 [0 0 0 0 1 1 1 1 1 1 1 1 0 0 0 0]
 [0 0 1 1 0 0 1 1 1 1 0 0 1 1 0 0]
 [0 1 0 1 1 0 1 0 0 1 0 1 1 0 1 0]
 [0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1]]
j_1: [0, 5, 2, 1, 15]
y_j1: [1 0 0 1 0]
c_1: [1 1 0 0 0 0 1 1 0 0 1 1 1 1 0 0]
e_1: [0 0 0 0 0 0 1 0 1 1 1 1 0 1 1 0]
d_1: 7


In [3]:
g2 = np.copy(g1)
g2[0] += g2[2]
g2[1] += g2[2]
print("g_2:")
print(g2)

j2 = generate_j(g2)
yj2 = np.array([y[pos] for pos in j2])
print("j_2: " + str(j2))
print("y_j2: " + str(yj2))

c2 = yj2 @ g2
e2 = y - c2
print("c_2: " + str(c2))
print("e_2: " + str(e2))
print("d_2: " + str(sum(to_array(e2))))

g_2:
[[1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0]
 [0 0 1 1 1 1 0 0 0 0 1 1 1 1 0 0]
 [0 0 1 1 0 0 1 1 1 1 0 0 1 1 0 0]
 [0 1 0 1 1 0 1 0 0 1 0 1 1 0 1 0]
 [0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1]]
j_2: [0, 5, 7, 1, 15]
y_j2: [1 0 1 1 0]
c_2: [1 1 0 0 0 0 1 1 0 0 1 1 1 1 0 0]
e_2: [0 0 0 0 0 0 1 0 1 1 1 1 0 1 1 0]
d_2: 7


In [4]:
g3 = np.copy(g2)
g3[3] += g3[4]
g3[2] += g3[4]
print("g_3:")
print(g3)

j3 = generate_j(g3)
yj3 = np.array([y[pos] for pos in j3])
print("j_3: " + str(j3))
print("y_j3: " + str(yj3))

c3 = yj3 @ g3
e3 = y - c3
print("c_3: " + str(c3))
print("e_3: " + str(e3))
print("d_3: " + str(sum(to_array(e3))))

g_3:
[[1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0]
 [0 0 1 1 1 1 0 0 0 0 1 1 1 1 0 0]
 [0 0 1 1 0 0 1 1 0 0 1 1 0 0 1 1]
 [0 1 0 1 1 0 1 0 1 0 1 0 0 1 0 1]
 [0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1]]
j_3: [0, 5, 7, 1, 9]
y_j3: [1 0 1 1 1]
c_3: [1 1 0 0 0 0 1 1 1 1 0 0 0 0 1 1]
e_3: [0 0 0 0 0 0 1 0 0 0 0 0 1 0 0 1]
d_3: 3
