# Алгебраические коды

## Терминология

Будем называть кодом некоторое пространство $C$ над полем $F$.

Линейным блоковым кодом будем называть $k$-мерное подпространство $n$-мерного векторного пространства над полем $GF(q)$.

## Информационная совокупность

Информационная совокупность кода $C$ над полем $F$ это такое минимальное подмножество координат $J$, что все элементы $F^{|J|}$ в этих координатах различны.

Информационная совокупность линейного кода $C \subset \mathbb{F}_q^n$ это такое множество координат $J = \{j_1, j_2,  \dots j_k\}$, что для любого $f \in \mathbb{F}_q^k$ существует единственное кодовое слово $c \in C$ такое, что для всех $i \in [1, k]$ верно $c_{j_i} = f_i$.

Проверочной совокупностью называются все координаты, не являющиеся информационными.

## Декодирование по информационным совокупностям

Пусть $y = c + e$, где $c$ — исходный вектор, $y$ — принятый вектор, а $e$ — вектор ошибки. Информационная совокупность $J$ называется свободной от ошибок, если для всех $i \in J$ верно $e_i = 0$. Если её удалось найти, то можно восстановить $c$ (исходя из определения $J$).

Общий алгоритм декодирования следующий. Пройдёмся по всем возможным $J$. Вычислим для каждой $J$ восстановленный вектор $c_J$. Результатом будет являться $\underset{c_J}{argmin} d_H(c_J, y)$.

Для линейных кодов каждая возможная информационная совокупность $J$ соответствует некоторой матрице $G_J$, полученной из порождающей матрицы $G$ путём комбинации линейных преобразований над строками, такой, что столбцы с позициями из $J$ образуют единичную матрицу в $G_J$. Тогда $c_J = y_J \cdot G_J$.

Далее будет показан пример перебора таких информационных совокупностей.

In [1]:
from algebra.binary import binary_array

g = binary_array([[1] * 8 + [0] * 8, ([1] * 4 + [0] * 4) * 2, ([1] * 2 + [0] * 2) * 4, [1, 0] * 8, [1] * 16])
print("g:")
print(g)

y = binary_array([1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0])
print("y: " + str(y))

g:
[[1 1 1 1 1 1 1 1 0 0 0 0 0 0 0 0]
 [1 1 1 1 0 0 0 0 1 1 1 1 0 0 0 0]
 [1 1 0 0 1 1 0 0 1 1 0 0 1 1 0 0]
 [1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0]
 [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]]
y: [1 1 0 0 0 0 0 1 1 1 0 0 1 0 1 0]


In [2]:
from algebra.binary import to_array
import numpy as np

g1 = np.copy(g)
g1 += np.array([g1[0] if i != 0 else [0] * len(g1[0]) for i in range(len(g1))])
g1[1], g1[3] = g1[3], g1[1].copy()
g1[0] += g1[1]
g1[0] += g1[2]
g1[1] += g1[3]
print("g_1:")
print(g1)

y1 = np.array([y[0], y[1], y[2], y[5], y[15]])
c1 = y1 @ g1
e1 = y - c1
print("c1: " + str(c1))
print("e1: " + str(e1))
print("d1: " + str(sum(to_array(e1))))

g_1:
[[1 0 0 1 1 0 0 1 0 1 1 0 0 1 1 0]
 [0 1 0 1 1 0 1 0 0 1 0 1 1 0 1 0]
 [0 0 1 1 0 0 1 1 1 1 0 0 1 1 0 0]
 [0 0 0 0 1 1 1 1 1 1 1 1 0 0 0 0]
 [0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1]]
c1: [1 1 0 0 0 0 1 1 0 0 1 1 1 1 0 0]
e1: [0 0 0 0 0 0 1 0 1 1 1 1 0 1 1 0]
d1: 7


In [3]:
g2 = np.copy(g1)
g2[0] += g2[2]
g2[3] += g2[2]
print("g_2:")
print(g2)

y2 = np.array([y[0], y[1], y[7], y[5], y[15]])
c2 = y2 @ g2
e2 = y - c2
print("c2: " + str(c2))
print("e2: " + str(e2))
print("d2: " + str(sum(to_array(e2))))

g_2:
[[1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0]
 [0 1 0 1 1 0 1 0 0 1 0 1 1 0 1 0]
 [0 0 1 1 0 0 1 1 1 1 0 0 1 1 0 0]
 [0 0 1 1 1 1 0 0 0 0 1 1 1 1 0 0]
 [0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1]]
c2: [1 1 0 0 0 0 1 1 0 0 1 1 1 1 0 0]
e2: [0 0 0 0 0 0 1 0 1 1 1 1 0 1 1 0]
d2: 7


In [4]:
g3 = np.copy(g2)
g3[1] += g3[4]
g3[1] += g3[4]
print("g_3:")
print(g3)

y3 = np.array([y[0], y[1], y[7], y[5], y[9]])
c3 = y3 @ g3
e3 = y - c3
print("c3: " + str(c3))
print("e3: " + str(e3))
print("d3: " + str(sum(to_array(e3))))

g_3:
[[1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0]
 [0 1 0 1 1 0 1 0 0 1 0 1 1 0 1 0]
 [0 0 1 1 0 0 1 1 1 1 0 0 1 1 0 0]
 [0 0 1 1 1 1 0 0 0 0 1 1 1 1 0 0]
 [0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1]]
c3: [1 1 0 0 0 0 1 1 1 1 0 0 0 0 1 1]
e3: [0 0 0 0 0 0 1 0 0 0 0 0 1 0 0 1]
d3: 3
